# Generated by Django 4.1.5 on 2023-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=10)),
                ('access_level', models.CharField(max_length=10)),
            ],
        ),
    ]
